enum RoleEnum {
  SUPERADMINISTRATOR = "SUPERADMINISTRATOR",
  ADMINISTRATOR = "ADMINISTRATOR",
  MEDICO = "MEDICO",
  ENFERMERA = "ENFERMERA",
  FARMACEUTICO = "FARMACEUTICO",
  TECNICO = "TECNICO",
  AUXILIAR = "AUXILIAR",
  PACIENTE = "PACIENTE",
  FAMILIAR = "FAMILIAR",
  EMPLEADO = "EMPLEADO",
  PROVEEDOR = "PROVEEDOR",
  CLIENTE = "CLIENTE",
  CUSTOMER = "CUSTOMER",
}

export default RoleEnum;
